### ISSUE TITLE
Fehler beim Installieren

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/fa_iconpicker#2]
Moin.
Ich nutze zwar den Picker nicht, habe ihn aber für die mal zum Test rausgesucht.

Leider kommt gleich beim Installieren folgender Fehler im Rex 5.12.1 bei mir:

`Argument 1 passed to Symfony\Component\Yaml\Yaml::parse() must be of the type string, null given, called in C:\webserver7.4\htdocs\web1.localhost.de\redaxo\src\core\lib\util\string.php on line 146`

**TypeError:** Argument 1 passed to Symfony\Component\Yaml\Yaml::parse() must be of the type string, null given, called in C:\webserver7.4\htdocs\web1.localhost.de\redaxo\src\core\lib\util\string.php on line 146
**File:** redaxo\src\core\vendor\symfony\yaml\Yaml.php
**Line:** 76

<details>
<summary>Stacktrace</summary>

| Function                           | File                                                   | Line     |
| ---------------------------------- | ------------------------------------------------------ | -------- |
| Symfony\Component\Yaml\Yaml::parse | redaxo\src\core\lib\util\string.php                    | 146      |
| rex_string::yamlDecode             | redaxo\src\addons\fa_iconpicker\lib\rex.fa.package.php | 343      |
| rex_fa_package::import             | redaxo\src\addons\fa_iconpicker\install.php            | 33       |
| include                            | redaxo\src\core\lib\packages\package.php               | 280      |
| rex_package->includeFile           | redaxo\src\core\lib\packages\manager.php               | 143      |
| rex_package_manager->install       | redaxo\src\core\lib\packages\addons\manager.php        | 27       |
| rex_addon_manager->install         | redaxo\src\core\lib\packages\api_package.php           | 34       |
| rex_api_package->execute           | redaxo\src\core\lib\api_function.php                   | 180      |
| rex_api_function::handleCall       | redaxo\src\core\backend.php                            | 229      |
| require                            | redaxo\src\core\boot.php                               | 141      |
| require                            | redaxo\index.php                                       | 9        |

</details>
<details>
<summary>System report (REDAXO 5.12.1, PHP 7.4.9, MariaDB 10.4.14)</summary>
</details>

**Comment by bitshiftersgmbh** [comment]
@iceman-fx Kannst du mal schauen, ob `/redaxo/data/addons/fa_iconpicker/packages/free/free-5.15.2/` existiert und wenn ja ob du von dort aus zu `/metadata/icons.yml` weiter kommst?

**Comment by skerbis** [comment]
Wenn nein, wurde ggf. das package nicht entzipt? @iceman-fx

**Comment by iceman-fx** [comment]
Ja, /redaxo/data/addons/fa_iconpicker/packages/free/free-5.15.2/ existiert.
Und ja, auch /metadata/icons.yml existiert.

**Comment by eaCe** [comment]
Habe hier den gleichen Fehler, wobei "/redaxo/data/addons/fa_iconpicker/packages/free/free-5.15.2/" nicht existiert, ebenso die gesuchte `icons.yml` in https://github.com/FriendsOfREDAXO/fa_iconpicker/blob/abd7f59ff76c4c5d4c3dec1da8b3165be32a4813/lib/rex.fa.package.php#L343

**Comment by bitshiftersgmbh** [comment]
Gute Hinweise, danke! Hab diese Woche keine Zeit werde aber ab Ende November hier nochmal nachlegen.

@eaCe wenn du den Ordner selbst anlegst und den Fehler damit umgehst, geht danach sonst alles (abgesehen vom Installieren neuer Pakete)?

**Comment by eaCe** [comment]
@bitshiftersgmbh yupp, dann geht soweit erst mal alles.

**Comment by bitshiftersgmbh** [comment]
Problem war, dass unter bestimmten Umständen die Ordner `/packages/free/` und `/packages/pro/` nicht mit angelegt wurden und deshalb bei Installationen schlicht die Files nicht korrekt entpackt wurden.

Da mit der 1.1.x die wenig robuste `.htacess`-Lösung abgeschafft ist und durch MediaManager-Typen ersetzt wird, sind besagte Ordner jetzt sogar komplett leer. So bekam ich nun endlich auch mal den eingangs genannten Fehler und konnte das Problem beheben.

Sollte auf jeden Fall mit den Release von 1.1.1 nachher behoben sein.

**Comment by bitshiftersgmbh** [comment]
@eaCe @iceman-fx Klappt bei euch der Spaß nun?

**Comment by eaCe** [comment]
@bitshiftersgmbh teste es Morgen noch mal

**Comment by eaCe** [comment]
@bitshiftersgmbh knallt nach wie vor, wie oben beschrieben beim install in Zeile 343 -> [fa_iconpicker/lib/rex.fa.package.php](https://github.com/FriendsOfREDAXO/fa_iconpicker/blob/abd7f59ff76c4c5d4c3dec1da8b3165be32a4813/lib/rex.fa.package.php#L343)

**Comment by bitshiftersgmbh** [comment]
Re-Install oder Update?
Und welche FA Version? (Ab 6.0.0. beta2 wird nicht mehr supportet. Fehlermeldung muss noch gemacht werden.)

**Comment by eaCe** [comment]
Neue Installation, neuste Version

**Comment by bitshiftersgmbh** [comment]
@eaCe Lass uns das mal zusammen in nem Web-Meeting anschauen bei Gelegenheit, OK?
Bin neugierig warum das noch bockt bei dir.

**Comment by iceman-fx** [comment]
Habe es gerade mit der 1.2.0 auf einem anderen System versucht zu installieren:

**TypeError:** Argument 1 passed to Symfony\Component\Yaml\Yaml::parse() must be of the type string, null given, called in C:\webserver7.4\htdocs\web2.localhost.de\redaxo\src\core\lib\util\string.php on line 157
**File:** redaxo\src\core\vendor\symfony\yaml\Yaml.php
**Line:** 76

<details>
<summary>Stacktrace</summary>

| Function                           | File                                                   | Line     |
| ---------------------------------- | ------------------------------------------------------ | -------- |
| Symfony\Component\Yaml\Yaml::parse | redaxo\src\core\lib\util\string.php                    | 157      |
| rex_string::yamlDecode             | redaxo\src\addons\fa_iconpicker\lib\rex.fa.package.php | 343      |
| rex_fa_package::import             | redaxo\src\addons\fa_iconpicker\install.php            | 39       |
| require                            | redaxo\src\core\lib\packages\package.php               | 280      |
| rex_package->includeFile           | redaxo\src\core\lib\packages\manager.php               | 137      |
| rex_package_manager->install       | redaxo\src\core\lib\packages\addons\manager.php        | 27       |
| rex_addon_manager->install         | redaxo\src\core\lib\packages\api_package.php           | 34       |
| rex_api_package->execute           | redaxo\src\core\lib\api_function.php                   | 182      |
| rex_api_function::handleCall       | redaxo\src\core\backend.php                            | 235      |
| require                            | redaxo\src\core\boot.php                               | 143      |
| require                            | redaxo\index.php                                       | 9        |

</details>

<summary>System report (REDAXO 5.14.2, PHP 7.4.9, MariaDB 10.4.14)</summary>

**Comment by iceman-fx** [comment]
Gibt es schon eine Lösung für das aktuelle Install-Problem (19.12.2022) ?
Das besteht immer noch - auch in Verbindung mit Rex 5.14.3

**Comment by bitshiftersgmbh** [comment]
Hey @iceman-fx . Hab's auf dem Schirm, bin diese Woche aber noch bissl *unter Wasser*. Lege es mir für kommende Woche auf Wiedervorlage. Evtl. schreib ich dich dann auch nochmal im Chat an.

**Comment by iceman-fx** [comment]
ok, danke.

**Comment by alxndr-w** [comment]
Besteht der Fehler bei der Installation immer noch?

Falls es nur um kostenlose FA-Icons geht, habe ich das Addon eben wiederbelebt: https://github.com/friendsofredaxo/iconpicker
