### ISSUE TITLE
Auf FA Version 6.2 updaten

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/fa_iconpicker#6]
**Feature description / Feature Beschreibung**

> Der Release von FA Version 6 steht aktuell hinter einem großen Fragezeichen. Im Oktober 2021 entschied man sich, den /metadata/-Ordner aus den FA6-Archiven zu entfernen und stattdessen auf die offizielle GraphQL-API zu verweisen. Gegenwärtig ist FA6 daher nur bis zur Version beta 1 unterstützt. Ihr könnt diese [hier](https://fontawesome.com/releases/6.0.0-beta1/web/download) herunterladen.

Das kann ich nicht erkennen.

![image](https://user-images.githubusercontent.com/3855487/197400202-62d49536-f6b7-46b9-b0fd-aeaf4e4a07d6.png)

**Comment by skerbis** [comment]
lieber @alxndr-w das hat sich längst erledigt. Es wurde auch aufgrund meines Drucks auf die Entwickler wieder eingeführt.

**Comment by alxndr-w** [comment]
Also ist die README falsch, der Rest passt?

**Comment by skerbis** [comment]
ja und ich habe gerade die 6.2 dazu gepackt ... gerne testen

**Comment by alxndr-w** [comment]
Thx
