### ISSUE TITLE
Größenbeschränkung auf 50 MB

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/fa_iconpicker#8]
die aktuellen Pro-Pakete sind größer als 50 MB und können nicht hochgeladen werden.

**Comment by alxndr-w** [comment]
Woher kommt das Limit?

**Comment by skerbis** [comment]
scheint so von hier: https://github.com/FriendsOfREDAXO/fa_iconpicker/blob/d24b14b6e721f27787af6c7443754aa950a99e27/assets/js/fa-iconpicker.js#L1171

**Comment by bitshiftersgmbh** [comment]
Kümmer mich drum.

**Comment by skerbis** [comment]
Wollte da nicht dran gehen, weil ich nicht weiß ob du das js mit irgendeinem Workflow baust
